name: check compatibility

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      working-directory:
        required: true
        default: 'libs/upstage'

env:
  WORKING_DIRECTORY: ${{ github.event.inputs.working-directory || 'libs/upstage' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

  test:
    name: test
    needs: [build]
    uses: ./.github/workflows/_test.yml
    secrets: inherit
    with:
      working-directory: ${{ env.WORKING_DIRECTORY }}

  compile-integration-tests:
    name: compile integration test
    needs: [build]
    uses: ./.github/workflows/_compile_integration_test.yml
    secrets: inherit
    with:
      working-directory: ${{ env.WORKING_DIRECTORY }}

  integration_test:
    name: integration test
    needs: [build]
    uses: ./.github/workflows/_integration_test.yml
    secrets: inherit
    with:
      working-directory: ${{ env.WORKING_DIRECTORY }}

  ci_success:
    name: "CI Success"
    needs: [build, test, compile-integration-tests, integration_test]
    if: always()
    runs-on: ubuntu-latest
    env:
      JOBS_JSON: ${{ toJSON(needs) }}
      RESULTS_JSON: ${{ toJSON(needs.*.result) }}
      EXIT_CODE: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && '0' || '1' }}
    steps:
      - name: "CI Success"
        run: |
          echo $JOBS_JSON
          echo $RESULTS_JSON
          echo "Exiting with $EXIT_CODE"
          exit $EXIT_CODE
